spring:
  datasource:
    url: "jdbc:postgresql://ec2-54-83-55-125.compute-1.amazonaws.com:5432/d3v6cn6vg6oj80"
    username: "ddzqucrjdnsrjr"
    password: "5c5596e6244cadcef49044dbffb91a2b614a495b39f3ea9e3f5b4a5678c91068"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: "default"
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type: trace
        show_sql: true
        format_sql: true
        ddl-auto: create-drop
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  resources:
    chain:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE